version: '3'
services:
  postgres:
    build:
      context: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=school
      - POSTGRES_USER=enouvo
      - POSTGRES_PASSWORD=123qwe

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - postgres